# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 305cff6106246af653db6d1e7818406cd8816cb7fc94ae4fd243721736e8a61c651813a9b3411e76748fa053f267e604cdf8c87788787069a8943b7e14a4a1bc

test:
  secret_key_base: 65de8da8e026d6a028ac1287f5872768d99adef78e2a441add91aa9dd2326170d4ccd27b5ac622595af4250a56b550217dca98778b7ef7681dd365391e18fb70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
